language: rust
sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
  include:
      - rust: 1.5.0 # minimum supported rustc version
        env: FEATURES="--no-default-features"
      - rust: stable



before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH

script:
  - |
      travis-cargo build -- $FEATURES &&
      travis-cargo test -- $FEATURES &&
      travis-cargo doc -- $FEATURES &&
      echo "Testing README" &&
      rustdoc --test README.md -L dependency=./target/debug/deps --extern nickel=./target/debug/libnickel.rlib

after_success:
  - |
      (echo "docs.nickel.rs" > target/doc/CNAME) &&
      travis-cargo --only stable doc-upload

